# Generated by Django 5.2.1 on 2025-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_partial_paid',
            field=models.BooleanField(default=False),
        ),
    ]
